### ISSUE TITLE
tests randomly failing on Windows during GitHub Action

### ISSUE THREAD

**Issue by misken** [misken/hillmaker#69]
For no reason, all of a sudden my automated tests on GH Actions were failing just on Windows but passing on Ubuntu. Some hunting led to this issue:

https://github.com/microsoft/azure-pipelines-tasks/issues/16426

Essentially the fix is specifying a non-tkinter matplotlib backend in the workflow. The suggested fix looks like:

```
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
     ...
```

After doing this, tests once again were passing on Windows.
